/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{html,js,svelte,ts}',
  ],
  safelist: [
    'html',
    'body',
    'hr',
    'abbr:where([title])',
    'h1',
    'h2',
    'h4',
    'h5',
    'h6',
    'a',
    'b',
    'strong',
    'code',
    'kbd',
    'samp',
    'pre',
    'small',
    'sub',
    'sup',
    'table',
    'button',
    'input',
    'optgroup',
    'select',
    'textarea',
    'progress',
    '[type="search"]',
    'summary',
    'blockquote',
    'dl',
    'dd',
    'figure',
    'p',
    'fieldset',
    'legend',
    'ol',
    'menu',
    'dialog',
    'input::-moz-placeholder',
    'textarea::-moz-placeholder',
    'input::placeholder',
    'textarea::placeholder',
    '[role="button"]',
    'svg',
    'video',
    'canvas',
    'audio',
    'iframe',
    'embed',
    'object',
    '[hidden]:where(:not([hidden="until-found"]))',
    'container',
    'static',
    'fixed',
    'left-0',
    'top-0',
    'top-full',
    'z-10',
    'z-20',
    'z-50',
    'z-[-1]',
    'mb-1',
    'mb-3',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-[-4rem]',
    'ml-2',
    'mt-2',
    'mt-4',
    'table',
    'contents',
    'hidden',
    'h-1',
    'h-12',
    'h-48',
    'h-6',
    'h-64',
    'h-8',
    'h-auto',
    'min-h-[44px]',
    'w-12',
    'w-48',
    'w-6',
    'w-8',
    'max-w-[90vw]',
    'max-w-full',
    'max-w-md',
    'max-w-xs',
    '-translate-y-2',
    'translate-y-2',
    '-rotate-45',
    'rotate-45',
    'cursor-pointer',
    'resize',
    'grid-cols-1',
    'flex-wrap',
    'justify-between',
    'gap-4',
    'gap-6',
    'overflow-hidden',
    'truncate',
    'rounded-full',
    'rounded-lg',
    'border',
    'bg-[rgba(8,8,28,0.7)]',
    'bg-[rgba(8,8,28,0.8)]',
    'bg-[rgba(8,8,28,0.95)]',
    'bg-[var(--accent)]',
    'bg-gray-800',
    'object-cover',
    'p-6',
    'px-4',
    'px-6',
    'px-8',
    'py-3',
    'py-4',
    'py-8',
    'pb-8',
    'pt-12',
    'text-2xl',
    'text-3xl',
    'text-[24px]',
    'text-lg',
    'text-sm',
    'text-xl',
    'text-xs',
    'font-semibold',
    'lowercase',
    'text-accent',
    'text-gray-300',
    'text-gray-400',
    'text-gray-600',
    'text-red-500',
    'opacity-0',
    'shadow-[-20px_20px_10px_rgba(0,0,0,0.5)]',
    'shadow-lg',
    'outline-none',
    'ring-2',
    'ring-blue-500',
    'ring-blue-600',
    'invert',
    'filter',
    'transition',
    'transition-opacity',
    'transition-transform',
    'duration-200',
    'duration-300',
    'hover:scale-105:hover',
    'hover:text-accent:hover',
    'hover:text-gray-300:hover',
    'hover:shadow-[-50px_50px_50px_rgba(0,0,0,0.5)]:hover',
    'focus:outline-none:focus',
    'focus:ring-2:focus',
    'sm:mx-0',
    'sm:mb-4',
    'sm:mb-[-6rem]',
    'sm:mt-6',
    'sm:flex',
    'sm:hidden',
    'sm:max-w-2xl',
    'sm:max-w-4xl',
    'sm:max-w-md',
    'sm:grid-cols-2',
    'sm:p-8',
    'sm:px-6',
    'sm:py-12',
    'sm:py-3',
    'sm:pt-16',
    'sm:text-left',
    'sm:text-2xl',
    'sm:text-3xl',
    'sm:text-4xl',
    'sm:text-base',
    'sm:text-lg',
    'sm:text-sm',
    'md:text-4xl',
    'md:text-lg',
    'lg:mb-[-7rem]',
    'lg:h-[500px]',
    'lg:max-w-lg',
    'lg:grid-cols-5',
    'lg:pt-20',
    'lg:text-4xl',
    'lg:text-5xl',
    'lg:text-lg',
    'lg:text-xl'
  ],
  theme: {
    extend: {
      fontFamily: {
        montserrat: ['Montserrat', 'sans-serif'],
      },
      colors: {
        primary: '#1a202c',
        accent: '#ed64a6',
      },
      backgroundImage: {
        gradient: 'linear-gradient(to bottom, #1a202c, #2d3748)',
      },
      transitionDuration: {
        200: '200ms',
        400: '400ms',
        600: '600ms',
        800: '800ms',
        1000: '1000ms'
      },
      transitionTimingFunction: {
        out: 'ease-out',
      },
    },
  },
  plugins: [],
};